### ISSUE TITLE
Causes ONLYOFFICE to crash

### ISSUE THREAD

**Issue by jamiejackherer** [ONLYOFFICE/plugin-autocomplete#26]
After installing this plugin, i can no longer use ONLYOFFICE as it says I am not connected to the internet (I am) and I canniot do anything in the application. Once this plugin was deleted everything works as expected.

**Comment by ShockwaveNN** [comment]
I don't think plugin may be a case of this, because our plugin architecture does not work that way

Could you specify
1. Which ONLYOFFICE product did you use and which version
2. Host OS
3. Version of `plugin-autocomplete` (git version if downloaded from git) or `.plugin` file
4. Screenshots of `I am not connected to the internet (I am) and I can not do anything in the application.` problems

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
